project:
  type: website

website:
  title: "ISSS624"
  search: 
    location: navbar
    type: textbox
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Ex1 - Geospatial Data Wrangling with R
            href: Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Ex1 - Choropleth Mapping with R
            href: Hands-on_Ex1/Hands-on_Ex1_2.qmd
          - text: Ex2 - Global and Local Measures of Spatial Autocorrelation
            href: Hands-on_Ex2/Hands-on_Ex2.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Ex3/Hands-on_Ex3.qmd
          - text: Hands-on Exercise 4
            href: Hands-on_Ex4/Hands-on_Ex4.qmd
          - text: Hands-on Exercise 5
      - text: In-class Exercises
        menu: 
          - text: Ex1 - Spatial Weights and Applications
            href: In-class_Ex1/In-class_Ex1.qmd
          - text: In-class Exercise 2
            href: Take-home_Ex1/Take-home_Ex1.qmd
          - text: In-class Exercise 3
          - text: In-class Exercise 4
          - text: In-class Exercise 5
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: Take-home_Ex1/Take-home_Ex1.qmd
          - text: Take-home Exercise 2
          - text: Take-home Exercise 3
          - text: Take-home Exercise 4
    right:
      - href: index.qmd
        text: Home
      - text: Errors Help
        href: Errors_Help.qmd
      - about.qmd
      - text: Github
        href: https://github.com/Yang621435?tab=repositories

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

