project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Ex1 - Geospatial Data Wrangling with R
            href: Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Ex1 - Choropleth Mapping with R
            href: Hands-on_Ex1/Hands-on_Ex1_2.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex2/Hands-on_Ex2.qmd
          - text: Hands-on Exercise 3
          - text: Hands-on Exercise 4
          - text: Hands-on Exercise 5
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
          - text: Take-home Exercise 2
          - text: Take-home Exercise 3
          - text: Take-home Exercise 4
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

